### PR TITLE
Added Master Thesis Formatting

### PR DESCRIPTION
**Pull request by jlshin**
Modified the templates and classes to comply with the UCSD master thesis guidelines. 
Modified table example - original example's table exceeded margin.

### CODE REVIEW

**Comment by bcipolli** [comment]
@jlshin can you let me know what the differences between the Masters and Ph.D theses are? If there's just a few, I'd rather have one thesis and set a flag at the beginning to switch between the two styles.

Thanks!

**Comment by jlshin** [comment]
Sure. 

Change in ucsd.cls and both template files:
1. "dissertation" and "Dissertation"  to  "Thesis" (note capitalization)
2. "Doctor of Philosophy" to "Master of Science"

In front_matter:
1. Remove Vita or indicate that it's optional 
2. Default committee members + chair = 3

**Comment by bcipolli** [comment]
Cool. Lemme think if there's a way to keep these two templates together, since they share so much. Will get back to ya soon!

**Comment by jlshin** [comment]
Thanks!!

**Comment by bcipolli** [comment]
@jlshin before I close this one, can you help me understand the change to the table width? Let's fix that in the master branch as well.

Or... could you fix that on the current master and then do a new pull request?

**Comment by jlshin** [comment]
@bcipolli It looks like you've fixed it. In the version I pulled the table was set using just inches. Here's a screenshot of the differences:

screen shot 2015-10-16 at 10 55 32 am

Originally the table was set to: 1in+2in+3in = 6in. Although this numerically complies with the OGS requirements of having a 1.5in/1in margin [8.5in-(1.5in + 1in) = 6in], the table in the pdf looked like:

screen shot 2015-10-16 at 11 13 20 am

Note I placed the red lines there because the person at the graduate office that was going over my formatting placed post-its where the red lines are and scrolled down the entire page to see if anything was outside these margins. 

Now that you've changed the template to take advantage of <code>\textwidth</code> it appears to have fixed the problem


screen shot 2015-10-16 at 11 18 30 am

**Comment by bcipolli** [comment]
Very cool. Thanks for the details! I guess it was fixed in my pull request to shift to a Lulu-compatible template. The Lulu formatting sucks, at least it's a start! Then we can get to print our theses in a better format than the same-old same-old ...

Will close this PR. Look forward to your next contribution, thanks for all the help...

**Pull request closed without merging**
